spring:
  datasource:
    url: jdbc:h2:~/membership
    # url: jdbc:h2:tcp://localhost/~/membership
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  config: classpath:log4j2.xml
  level:
    org.hibernate.SQL: debug


